import { Competition, RegisteredSchool, Submission } from './types';

export const MEDIA_UNIT_INFO = {
  name: 'Agradhi Media Unit',
  institution: 'Saranath College',
  tagline: 'All-Island Inter-School Media Competitions & Media Day 2026',
  email: 'agradhimedia@saranath.edu.lk',
  hotline: 'num_1 / num_2',
  address: 'Media Circle, Saranath College, Kuliyapitiya / Western Province, Sri Lanka',
  edition: '2026 Edition (8th Annual Assembly)',
};

export const SRI_LANKA_PROVINCES = [
  'Western Province',
  'Central Province',
  'Southern Province',
  'North Western Province',
  'Sabaragamuwa Province',
  'North Central Province',
  'Uva Province',
  'Northern Province',
  'Eastern Province',
];

export const INITIAL_COMPETITIONS: Competition[] = [
  {
    id: 'comp-shortfilm-2026',
    title: 'Silver Screen: Inter-School Short Film Festival',
    category: 'Short Film & Cinematography',
    slug: 'short-film-festival',
    description:
      'Original narrative or documentary short film competition under the theme "Unseen Truths: Resilient Horizons". Max running time: 8 minutes.',
    eligibility: 'Grades 9 - 13 (Open Category)',
    deadline: '2026-11-15',
    maxEntriesPerSchool: 2,
    status: 'open',
    prizePool: 'LKR 150,000 + Challenge Trophy & Laurels',
    guidelines: [
      'Duration: 3 to 8 minutes including title and credits.',
      'Resolution: Minimum 1080p FHD (16:9 or 2.39:1 aspect ratio).',
      'Original audio/BGM or royalty-free licensed audio must be declared.',
      'Google Drive link with viewer permissions enabled is required.',
      'Include a 150-word synopsis and production crew credits.',
    ],
    customFields: [
      {
        id: 'runtime_minutes',
        label: 'Exact Runtime (Minutes:Seconds)',
        type: 'text',
        required: true,
        placeholder: 'e.g. 06:45',
      },
      {
        id: 'aspect_ratio',
        label: 'Aspect Ratio & Resolution',
        type: 'select',
        required: true,
        options: ['1080p 16:9', '4K UHD 16:9', '2.39:1 Anamorphic', 'Other FHD'],
      },
      {
        id: 'crew_names',
        label: 'Key Crew Members (Director, DP, Editor)',
        type: 'textarea',
        required: true,
        placeholder: 'Director: Name (Gr. 12)\nDP: Name (Gr. 13)\nSound: Name (Gr. 11)',
      },
    ],
  },
  {
    id: 'comp-photography-2026',
    title: 'Aperture \'26: High-School Photography Salon',
    category: 'Photography',
    slug: 'photography-salon',
    description:
      'Visual storytelling through raw lens capture. Two sub-genres: Street Documentary & Environmental Portraiture.',
    eligibility: 'Grades 6 - 13 (Junior & Senior Divisions)',
    deadline: '2026-11-10',
    maxEntriesPerSchool: 4,
    status: 'open',
    prizePool: 'LKR 80,000 + Gold Medals & Exhibition Feature',
    guidelines: [
      'RAW EXIF data must be preserved inside the JPEG/TIFF image.',
      'Minimal post-processing permitted (cropping, exposure, color contrast). AI generation is strictly prohibited.',
      'Image file size must be at least 4MB and max 25MB.',
      'Provide title and contextual caption for the capture.',
    ],
    customFields: [
      {
        id: 'camera_gear',
        label: 'Camera Body & Lens Used',
        type: 'text',
        required: true,
        placeholder: 'e.g. Sony A7III + 35mm f/1.8 or Canon 80D',
      },
      {
        id: 'capture_location',
        label: 'Location & Date of Capture',
        type: 'text',
        required: true,
        placeholder: 'e.g. Pettah Floating Market, September 2026',
      },
      {
        id: 'division',
        label: 'Age Division',
        type: 'select',
        required: true,
        options: ['Junior Division (Grades 6-9)', 'Senior Division (Grades 10-13)'],
      },
    ],
  },
  {
    id: 'comp-announcing-2026',
    title: 'Voice of Truth: Trilingual News Reading & Announcing',
    category: 'News Reading & Announcing',
    slug: 'news-reading-announcing',
    description:
      'Premier broadcast competition evaluating voice modulation, articulation, composure, and teleprompter sight-reading in Sinhala & English.',
    eligibility: 'Grades 9 - 13 (Individual Contests)',
    deadline: '2026-11-20',
    maxEntriesPerSchool: 3,
    status: 'open',
    prizePool: 'LKR 90,000 + Best Broadcaster Accolade',
    guidelines: [
      'Submit unedited video recording of the student presenting provided sample news bulletin.',
      'Formal news anchor attire is mandatory.',
      'Clear audio recording without excessive room reverberation.',
      'Video file or unlisted YouTube link required.',
    ],
    customFields: [
      {
        id: 'language_stream',
        label: 'Medium / Language',
        type: 'select',
        required: true,
        options: ['Sinhala Medium', 'English Medium', 'Tamil Medium'],
      },
      {
        id: 'experience_years',
        label: 'Student School Media Experience (Years)',
        type: 'number',
        required: false,
        placeholder: 'e.g. 2',
      },
    ],
  },
  {
    id: 'comp-graphicdesign-2026',
    title: 'Pixel Craft: Graphic Design & Poster Artwork Contest',
    category: 'Graphic Design & Digital Art',
    slug: 'graphic-design-poster',
    description:
      'Digital poster design competition for upcoming National Youth Media Festival. Emphasis on typography, visual hierarchy, and brand concept.',
    eligibility: 'Grades 8 - 13',
    deadline: '2026-11-12',
    maxEntriesPerSchool: 3,
    status: 'open',
    prizePool: 'LKR 65,000 + Digital Graphics Trophy',
    guidelines: [
      'Dimensions: A3 (297 x 420 mm) at 300 DPI.',
      'Submit both print-ready PDF and original source file link (PSD/AI/Figma).',
      'Theme: "Empowering Voices in the Digital Era".',
    ],
    customFields: [
      {
        id: 'software_tools',
        label: 'Design Software Used',
        type: 'text',
        required: true,
        placeholder: 'e.g. Adobe Illustrator, Photoshop, Figma',
      },
      {
        id: 'design_concept',
        label: 'Design Philosophy / Rationale (50-100 words)',
        type: 'textarea',
        required: true,
        placeholder: 'Explain the choice of colors, typography and focal elements...',
      },
    ],
  },
  {
    id: 'comp-radioplay-2026',
    title: 'Sound Waves: Radio Drama & Acoustic Production',
    category: 'Radio Play & Audio Production',
    slug: 'radio-drama-production',
    description:
      'Original radio play or audio documentary featuring immersive foley sound effects, soundscapes, vocal acting, and sound engineering.',
    eligibility: 'Grades 9 - 13',
    deadline: '2026-11-18',
    maxEntriesPerSchool: 2,
    status: 'open',
    prizePool: 'LKR 75,000 + Sound Engineering Award',
    guidelines: [
      'Duration: 5 to 10 minutes maximum.',
      'Format: High-quality MP3 (320kbps) or WAV (24bit/48kHz).',
      'Must contain a complete script submission alongside audio file.',
    ],
    customFields: [
      {
        id: 'audio_format',
        label: 'Audio Master Format',
        type: 'select',
        required: true,
        options: ['Stereo WAV 24bit', 'MP3 320kbps', 'FLAC Lossless'],
      },
      {
        id: 'script_link',
        label: 'Script Document Google Drive Link',
        type: 'url',
        required: true,
        placeholder: 'https://drive.google.com/...',
      },
    ],
  },
];

export const INITIAL_SCHOOLS: RegisteredSchool[] = [
  {
    id: 'scl-ananda-colombo',
    name: 'Ananda College',
    registrationNumber: 'ACMC/2026/041',
    district: 'Colombo',
    province: 'Western Province',
    teacherInCharge: 'Mr. Chandana Wickramasinghe',
    teacherPhone: '+94 71 889 1234',
    mediaPresident: 'Methmika Jayasundara',
    presidentPhone: '+94 77 912 3456',
    email: 'media@ananda.sch.lk',
    password: 'password123',
    status: 'active',
    registeredAt: '2026-09-12',
    badgeCode: 'AMU-SCL-014',
  },
  {
    id: 'scl-royal-colombo',
    name: 'Royal College',
    registrationNumber: 'RCMU/2026/089',
    district: 'Colombo',
    province: 'Western Province',
    teacherInCharge: 'Mrs. Kumari Fernando',
    teacherPhone: '+94 70 234 5678',
    mediaPresident: 'Ranul Senaratne',
    presidentPhone: '+94 76 543 2198',
    email: 'mediaunit@royalcollege.lk',
    password: 'password123',
    status: 'active',
    registeredAt: '2026-09-15',
    badgeCode: 'AMU-SCL-015',
  },
  {
    id: 'scl-dharmaraja-kandy',
    name: 'Dharmaraja College',
    registrationNumber: 'DCMU/2026/012',
    district: 'Kandy',
    province: 'Central Province',
    teacherInCharge: 'Mr. Sarath Bandara',
    teacherPhone: '+94 72 345 6789',
    mediaPresident: 'Hirun Dissanayake',
    presidentPhone: '+94 78 876 5432',
    email: 'media@dharmaraja.lk',
    password: 'password123',
    status: 'active',
    registeredAt: '2026-09-18',
    badgeCode: 'AMU-SCL-016',
  },
  {
    id: 'scl-maliyadeva-kurunegala',
    name: 'Maliyadeva College',
    registrationNumber: 'MCMU/2026/027',
    district: 'Kurunegala',
    province: 'North Western Province',
    teacherInCharge: 'Mrs. Nelum Jayawardena',
    teacherPhone: '+94 71 456 7890',
    mediaPresident: 'Kavindu Senanayake',
    presidentPhone: '+94 75 432 1098',
    email: 'media@maliyadeva.edu.lk',
    password: 'password123',
    status: 'active',
    registeredAt: '2026-09-20',
    badgeCode: 'AMU-SCL-017',
  },
];

export const INITIAL_SUBMISSIONS: Submission[] = [
  {
    id: 'sub-001',
    competitionId: 'comp-shortfilm-2026',
    competitionTitle: 'Silver Screen: Inter-School Short Film Festival',
    schoolId: 'scl-ananda-colombo',
    schoolName: 'Ananda College',
    category: 'Short Film & Cinematography',
    studentName: 'Methmika Jayasundara & Crew',
    studentGrade: 'Grade 12-B',
    studentContact: '+94 77 912 3456',
    entryTitle: 'Shadows of Pettah: The Lost Railway',
    submissionLink: 'https://drive.google.com/drive/folders/sample-ananda-film',
    synopsis: 'A heartfelt documentary portraying three generations of railway porters at Colombo Fort station, filmed in 4K with natural ambient recordings.',
    status: 'verified',
    submittedAt: '2026-09-22',
    score: 88,
    judgeFeedback: 'Outstanding cinematography and sound design. Color grading matches the narrative tone exceptionally well.',
  },
  {
    id: 'sub-002',
    competitionId: 'comp-photography-2026',
    competitionTitle: 'Aperture \'26: High-School Photography Salon',
    schoolId: 'scl-royal-colombo',
    schoolName: 'Royal College',
    category: 'Photography',
    studentName: 'Dineth Perera',
    studentGrade: 'Grade 11',
    studentContact: '+94 71 112 2334',
    entryTitle: 'Monsoon Rhythm at Beira Lake',
    submissionLink: 'https://drive.google.com/drive/folders/sample-royal-photo',
    synopsis: 'Candid black-and-white frame showing a school student shielding his canvas under unexpected Colombo rain.',
    status: 'shortlisted',
    submittedAt: '2026-09-24',
    score: 93,
    judgeFeedback: 'Exceptional dynamic contrast and emotive storytelling. Selected for grand exhibition showcase.',
  },
  {
    id: 'sub-003',
    competitionId: 'comp-announcing-2026',
    competitionTitle: 'Voice of Truth: Trilingual News Reading & Announcing',
    schoolId: 'scl-maliyadeva-kurunegala',
    schoolName: 'Maliyadeva College',
    category: 'News Reading & Announcing',
    studentName: 'Sithum Ranasinghe',
    studentGrade: 'Grade 13',
    studentContact: '+94 75 432 1098',
    entryTitle: 'Sinhala News Bulletin Final Presentation',
    submissionLink: 'https://youtu.be/sample-maliyadeva-news',
    synopsis: 'Studio recording of prime-time news bulletin reading, demonstrating standard Sinhala broadcast phonetics.',
    status: 'under_review',
    submittedAt: '2026-09-28',
  },
];
